repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --scripts-are-modules]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: '1.8.5'
    hooks:
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: nbqa-mypy
        args: [--ignore-missing-imports, --scripts-are-modules]
