name: droplet-hr
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - jupyterlab
  - pip:
    - imagecodecs
    - ipympl
    - ipywidgets  # required for tqdm
    - matplotlib
    - numpy
    - opencv-python-headless
    - pandas
    - scikit-image
    - scipy
    - tifffile
    - tqdm
